language: ruby
cache: bundler
addons:
    code_climate:
        repo_token: c4423709ed4e210ed3ea4330ad3275ba67b5734a3d9c73934440230a4dd67a9e
rvm:
  - 2.3.0
env:
  global:
    - RACK_ENV=test
branches:
  only:
    - master
#addons:
#  sauce_connect: true
install:
  - bundle install
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - rake db:migrate
  - rake seed
script:
  - rspec
deploy:
  provider: heroku
  api_key: "9951e24c-b489-48fe-8a60-b325e8d850dd"
  app: cobra-traffic
  skip_cleanup: true
  run: "rake db:migrate"
