language: ruby
cache: bundler
rvm:
  - 2.3.0
env:
  global:
    - RACK_ENV=test
branches:
  only:
    - master
install:
  - bundle install
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - rake db:migrate
script:
  - rake test --trace
deploy:
  provider: heroku
  api_key: "9951e24c-b489-48fe-8a60-b325e8d850dd"
  app: cobra-traffic
  skip_cleanup: true
  run: "rake db:migrate"
